version: '3.8'

services:
  devops_db:
    container_name: devops_db
    image: postgres:latest
    env_file: 'backend/.env'
    ports:
      - "5432:5432"
    volumes:
      - devops-data:/var/lib/postgresql/data
    networks:
      - internal

  devops_backend:
    container_name: devops_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - devops_db
    networks:
      - internal
    environment:
      - POSTGRES_HOST=devops_db
    command: '/app/docker-dev-init.sh'

  devops_frontend:
    container_name: devops_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - internal

volumes:
  devops-data:
    driver: local

networks:
  internal:
