name: Staging CI/CD Pipeline

on:
  push:
    branches:
      - staging  
  pull_request:
    branches:
      - staging

jobs:
  build-and-deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.CLUSTER_LOCATION }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker images
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/devops-backend:latest ./backend
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/devops-backend:latest
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/devops-frontend:latest ./frontend
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/devops-frontend:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/